name: Deploy

on:
  repository_dispatch:
    types:
      - content_changed
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      version:
        required: true
        type: string
      region:
        required: false
        type: string
        default: eu-west-1
    secrets:
      ALDRA_GITHUB_BOT_TOKEN:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ inputs.environment || github.event.client_payload.environment }}-${{ github.ref }}
  cancel-in-progress: true

env:
  HUSKY: 0

permissions:
  id-token: write
  contents: read

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    if: ${{ inputs.environment || github.event.client_payload.environment }}
    environment: ${{ inputs.environment || github.event.client_payload.environment }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.version }}

      - uses: actions/setup-node@v4
        with:
          registry-url: https://npm.pkg.github.com
          node-version: 20
          cache: npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ALDRA_GITHUB_BOT_TOKEN }}

      - name: Install dependencies
        run: npm ci --quiet

      - name: Build
        run: npm run build
        env:
          OIDC_ISSUER: ${{ vars.OIDC_ISSUER }}
          OIDC_CLIENT_ID: ${{ vars.OIDC_CLIENT_ID }}
          OIDC_SCOPES: ${{ vars.OIDC_SCOPES }}
          SANITY_STUDIO_PROJECT_ID: ${{ vars.SANITY_STUDIO_PROJECT_ID }}
          SANITY_STUDIO_DATASET: ${{ vars.SANITY_STUDIO_DATASET }}
          SANITY_API_VERSION: ${{ vars.SANITY_API_VERSION }}
          GRAPHQL_API_URL: ${{ vars.GRAPHQL_API_URL }}

      - name: Install envsubst
        run: |
          sudo apt-get update
          sudo apt-get install gettext-base

      - name: Create configuration
        env:
          OIDC_ISSUER: ${{ vars.OIDC_ISSUER }}
          OIDC_CLIENT_ID: ${{ vars.OIDC_CLIENT_ID }}
          OIDC_SCOPES: ${{ vars.OIDC_SCOPES }}
          SANITY_STUDIO_PROJECT_ID: ${{ vars.SANITY_STUDIO_PROJECT_ID }}
          SANITY_STUDIO_DATASET: ${{ vars.SANITY_STUDIO_DATASET }}
          SANITY_API_VERSION: ${{ vars.SANITY_API_VERSION }}
          GRAPHQL_API_URL: ${{ vars.GRAPHQL_API_URL }}
        run: envsubst < ./config.template > ./lib/config.js;

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.region || github.event.client_payload.region || 'eu-west-1' }}
          role-to-assume: ${{ vars.AWS_ROLE_FOR_GITHUB_ACTIONS }}

      - name: Deploy to AWS S3 bucket
        run: aws s3 sync lib s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
